name: Make

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  make-all:
    name: Make all
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
      - uses: actions/checkout@v2
      - run: make
