name: Make

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  test-make:
    name: Make all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - run: make
