name: Make

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  test-make:
    name: Make all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Makefile
        run: make
